import Head from 'next/head';
import React from 'react';

const Blogs = () => {
  return (
    <div className="h-[80vh] flex justify-center items-center">
      <Head>
        <title>Blogs - noyandey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-center font-code my-4">
        <h1 className="text-4xl font-semibold">Coming <span className="text-cyan-500">Soon</span></h1>
      </div>
    </div>
  );
};

export default Blogs;