import Head from 'next/head'
import Banner from '../components/Banner/Banner'
import Contact from '../components/Contact/Contact'
import Projects from '../components/Projects/Projects'
import Skills from '../components/Skills/Skills'

export default function Home({ projects }) {
  return (
    <div>
      <Head>
        <title>Home - noyandey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner></Banner>
        <Skills></Skills>
        <Projects allProjects={projects}></Projects>
        <Contact></Contact>
      </main>
    </div>
  )
}

export const getServerSideProps = async () => {
  const res = await fetch("https://noyan-portfolio-server.vercel.app/projects");
  const data = await res.json();

  return {
    props: {
      projects: data
    }
  }
}